<h4><?=$this->translate('password_has_been_reset')?></h4>
<hr/>
<h6><?=$this->translate('this_is_your_login_information')?></h6>
<dl class="dl-horizontal">
	<dt><?=$this->translate('username')?> :</dt>
	<dd><?=$this->auth_access_username_identity?></dd>
	<dt><?=$this->translate('password')?> :</dt>
	<dd><?=$this->auth_access_credential?></dd>
</dl>
<hr/>
<h5>
	<a href="<?=$this->serverUrl().$this->url('AccessControl/Authenticate')?>"><?=$this->translate('sign_in')?></a>
</h5>