<?php if($this->emailChanged === true){
	echo $this->alert('email_has_been_changed_email_has_been_sent','alert-success',false);
?>
<button class="btn btn-small btn-primary pull-right" type="button" data-dismiss="modal"><?=$this->translate('close_modal')?></button>
<?php }
else{
	echo $this->form($this->form,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL,true);
?>
<script type="text/javascript">
	document.id('user_new_email').focus();
</script>
<?php } ?>
