<?php if($this->passwordChanged === true){
	echo $this->alert('password_has_been_changed','alert-success',false);
?>
<button class="btn btn-small btn-primary pull-right" type="button" data-dismiss="modal"><?=$this->translate('close_modal')?></button>
<?php }
else{
	echo $this->form($this->form,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL,true);
?>
<script type="text/javascript">
	document.id('user_password').focus();
</script>
<?php } ?>
