<?php if($this->passwordChanged === true){ ?>
<div class="alert alert-success">
	<?=$this->translate('password_has_been_changed')?>
</div>
<button class="btn btn-small btn-primary pull-right" type="button" data-dismiss="modal"><?=$this->translate('close_modal')?></button>
<?php }
else{
	echo $this->form($this->form,null,array('ajax' => true));
?>
<script type="text/javascript">
	document.id('user_password').focus();
</script>
<?php } ?>
