<?php if($this->avatarUpdated){
	echo $this->alert('avatar_has_been_changed','alert-success',false);
?>
<script type="text/javascript">
	if('undefined' != typeof oController)oController.setUserAvatar(<?=$this->escapeJson($this->userAvatar($this->layout()->loggedUser))?>);
</script>
<button class="btn btn-small btn-primary pull-right" type="button" data-dismiss="modal"><?=$this->translate('close_modal')?></button>
<?php }
else{
	echo $this->form($this->form,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL,true);
?>
<script type="text/javascript">
	if(document.id){
		var oNewUserAvatar = document.id('user_new_avatar');
		if(oNewUserAvatar)oNewUserAvatar.focus();
	}
</script>
<?php } ?>