<?php if($this->passwordChanged === true){ ?>
<div class="alert alert-success">
	<?=$this->translate('password_has_been_changed')?>
</div>
<button class="btn btn-small btn-primary pull-right" type="button" data-dismiss="modal"><?=$this->translate('close_modal')?></button>
<?php }
else{
	if(!empty($this->error))echo '<div class="alert alert-error">'.$this->error.'</div>';
	echo $this->form($this->form,null,array(
		'ajax' => true,
		'elements' => array(
			'submit' => array('class' => 'btn-large')
		)
	));
?>
<script type="text/javascript">
	document.id('user_password').focus();
</script>
<?php } ?>
