<?php if($this->passwordChanged === true){ ?>
<div class="alert alert-success">
	<?=$this->translate('password_changed')?>
</div>
<?php }
else{
	if(!empty($this->error))echo '<div class="alert alert-error">'.$this->error.'</div>';
	echo $this->formTwb($this->form,null,array('elements' => array(
		'submit' => array('class' => 'btn-large')
	)));
}
?>
<script type="text/javascript">
	document.id('user_password').focus();
</script>