<h3><?=$this->layout()->title?></h3>
<div class="well">
	<?=$this->translate('new_user')?> ? <a href="<?=$this->url('zf2user/register')?>"><?=$this->translate('sign_up')?> </a> !
</div>
<?=$this->formTwb($this->form,null,array('elements' => array(
	'user_email' => array(
		'class' => 'input-medium',
		'prependIcon' => 'icon-envelope'
	),
	'user_password' => array(
		'class' => 'input-medium',
		'prependIcon' => 'icon-lock'
	),
	'submit' => array(
		'class' => 'btn-large',
	)
)))?>