<h4><?=$this->translate('welcome_to').' '.$this->translate('application_name')?> !</h4>
<hr/>
<?php if($this->auth_access_username_identity){ ?>
<h6><?=$this->translate('this_is_your_login_information')?></h6>
<dl class="dl-horizontal">
	<dt><?=$this->translate('username')?> :</dt>
	<dd><?=$this->auth_access_username_identity?></dd>
	<dt><?=$this->translate('password')?> :</dt>
	<dd><?=$this->auth_access_credential?></dd>
</dl>
<hr/>
<?php } ?>
<h5>
	<?=$this->translate('please_confirm_your_email')?> :
	<a href="<?=$this->serverUrl().$this->url('AccessControl/ConfirmEmail',array(
		'public_key' => $this->auth_access_public_key,
		'email_identity' => $this->auth_access_email_identity
	))?>"><?=$this->translate('confirm_email')?></a>.
</h5>