<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2User\Module' => __DIR__ . '/Module.php',
    'ZF2User\Controller\UserController' => __DIR__ . '/src/ZF2User/Controller/UserController.php',
	'ZF2User\Service\UserService' => __DIR__ . '/src/ZF2User/Service/UserService.php',
);
