<h3><?=$this->layout()->title?></h3>
<div class="well">
<?=$this->translate('new_user').' ? <a href="'.$this->url('User/register').'">'.$this->translate('sign_up').'</a> ! | '.$this->translate('forgot_your_password').' ? <a href="'.$this->url('User/forgotten-password').'">'.$this->translate('reset_password').'</a>'?>
</div>
<?php
	if(!empty($this->error)){
		if($this->error === $this->translate('user_state_pending'))$this->error .= '
			<br/><br/>
			<a href="javascript:oController.sendConfirmationEmail('.$this->escapeHtmlAttr($this->escapeJson($this->form->get('user_email')->getValue())).');">
				'.$this->translate('resend_confirmation_email').'
			</a>
		';
		echo $this->alert($this->error,'alert-error',false);
	}
	echo $this->form($this->form);
?>
<fieldset>
	<legend><?=$this->translate('or_use_another_service')?></legend>
    <a class="btn btn-mini" href="<?=$this->url('User/login',array('service'=>'facebook'))?>"><i class="icon-facebook"></i> Facebook</a>
    <a class="btn btn-mini" href="<?=$this->url('User/login',array('service'=>'twitter'))?>"><i class="icon-twitter"></i> Twitter</a>
    <a class="btn btn-mini" href="<?=$this->url('User/login',array('service'=>'google'))?>"><i class="icon-google-plus"></i> Google+</a>
</fieldset>