<h3><?=$this->layout()->title?></h3>
<?php if($this->passwordReset === true){?>
<div class="alert alert-success">
	<?=$this->translate('password_reset_sent')?>
</div>
<?php }
else {
	if(!empty($this->error))echo '
		<div class="alert alert-error">
			'.$this->error.'<br/><br/>
			'.$this->translate('new_user').' ? <a href="'.$this->url('User/register').'">'.$this->translate('sign_up').'</a> !
		</div>
	';
	echo $this->form($this->form,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_INLINE);
}
?>
