<?php
// Generated by Zend Framework 2
return array(
    'Application\Module'                              => __DIR__ . '/Module.php',
    'Application\Controller\IndexController'          => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Factory\SessionManagerFactory'       => __DIR__ . '/src/Application/Factory/SessionManagerFactory.php',
    'Application\Form\AbstractForm'                   => __DIR__ . '/src/Application/Form/AbstractForm.php',
    'Application\Form\View\Helper\FormHelper'         => __DIR__ . '/src/Application/Form/View/Helper/FormHelper.php',
    'Application\Translator\Translator'               => __DIR__ . '/src/Application/Translator/Translator.php',
    'Application\Translator\TranslatorServiceFactory' => __DIR__ . '/src/Application/Translator/TranslatorServiceFactory.php',
    'Application\Validator\NoSpaces'                  => __DIR__ . '/src/Application/Validator/NoSpaces.php',
    'Application\View\Helper\EscapeJsonHelper'        => __DIR__ . '/src/Application/View/Helper/EscapeJsonHelper.php',
    'Application\View\Helper\JsControllerHelper'      => __DIR__ . '/src/Application/View/Helper/JsControllerHelper.php',
    'Application\View\Helper\SocialHelper'            => __DIR__ . '/src/Application/View/Helper/SocialHelper.php',
);