<div class="container" data-behavior="BS.Dropdown BS.DismissPopup">
	<header data-behavior="BS.Dropdown BS.DismissPopup"><?=$this->layout()->header?></header>
	<!--[if lt IE 7]><p class="chromeframe"><?=$this->translate('outdated_browser')?></p><![endif]-->
	<div class="row-fluid">
		<div class="span12"><?=$this->layout()->content?></div>
	</div>
	<hr>
	<footer><?=$this->layout()->footer?></footer>
</div>