<header data-behavior="BS.Dropdown BS.DismissPopup">
	<div class="navbar navbar-default" role="navigation">
		<div class="navbar-header">
			<a class="navbar-brand" href="<?=$this->url('Home')?>"><?=$this->translate('application_name')?></a>
		</div>
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
				<li<?=$this->layout()->matchedRouteName === 'Home'?' class="active"':''?>><a href="<?=$this->url('Home')?>"><?=$this->translate('home')?></a></li>
			</ul>
			<?=$this->header?>
		</div>
	</div>
</header>
<div class="container" data-behavior="BS.Dropdown BS.DismissPopup">
	<!--[if lt IE 7]><p class="chromeframe"><?=$this->translate('outdated_browser')?></p><![endif]-->
	<div class="well">
  		<h2><?=$this->layout()->title?></h2>
  		<?=$this->layout()->content?>
  	</div>
	<hr>
	<footer><?=$this->footer?></footer>
</div>