<?=$this->doctype()?>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
 	<head>
<?php
        echo $this->headTitle($this->translate('application_name'))->__invoke($this->layout()->title)->setSeparator(' - ')->setAutoEscape(false).
	 	$this->headMeta()
	 	->appendName('charset','utf-8')
	 	->appendName('viewport','width=device-width, initial-scale=1.0')
	 	->appendName('description',$this->translate('application_description'))
	 	->appendHttpEquiv('X-UA-Compatible','IE=edge,chrome=1').
       	$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon','href' => $this->basePath().'/assets/images/favicon.ico')).
       	$this->headScript();
?>
	</head>
	<body>
        <header data-behavior="BS.Dropdown BS.DismissPopup"><?=$this->layout()->header?></header>
        <div class="container" data-behavior="BS.Dropdown BS.DismissPopup">
        	<!--[if lt IE 7]><p class="chromeframe"><?=$this->translate('outdated_browser')?></p><![endif]-->
	    	<div class="row-fluid">
    			<div class="span12"><?=$this->layout()->content?></div>
    		</div>
			<hr>
            <footer>
            	<a href="<?=$this->url('home')?>"><?=$this->translate('application_name')?></a> |
				<a href="<?=$this->url('terms')?>"><?=$this->translate('terms')?></a> |
				<a href="<?=$this->url('privacy')?>"><?=$this->translate('privacy')?></a>
                <span class="pull-right">&copy; <?=$this->translate('application_name').' '.date('Y')?></span>
            </footer>

        </div>
        <!-- /container -->
        <?php
        	//Javascript files
       	 	echo $this->inlineScript();

       	 	//Google analytics
        	$this->social(\Application\View\Helper\SocialHelper::GOOGLE_ANALYTICS);

        	//Initalise js Controller
        	echo $this->jsController();
        ?>
    </body>
</html>