<?=$this->doctype()?>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
 	<head>
<?php
        echo $this->headTitle($this->translate('application_name'))->__invoke($this->layout()->title)->setSeparator(' - ')->setAutoEscape(false).
	 	$this->headMeta()
	 	->appendName('charset','utf-8')
	 	->appendName('viewport','width=device-width, initial-scale=1.0')
	 	->appendName('description',$this->translate('application_description'))
	 	->appendHttpEquiv('X-UA-Compatible','IE=edge,chrome=1').
       	$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon','href' => $this->basePath().'/assets/images/favicon.ico')).
       	$this->headScript();
?>
	</head>
	<body>
        <!--[if lt IE 7]><p class="chromeframe"><?=$this->translate('outdated_browser')?></p><![endif]-->
        <?=$this->layout()->header?>
        <div class="container">
			<?=$this->layout()->content?>
			<hr>
            <footer>
                <p>&copy; <?=$this->translate('application_name').' '.date('Y')?></p>
            </footer>

        </div>
        <!-- /container -->
        <?=$this->inlineScript().$this->social(\Application\View\Helper\Social::GOOGLE_ANALYTICS)?>
    </body>
</html>