<h3><?=$this->layout()->title?></h3>
<?php
	if($this->isValid === true)echo $this->alert('registration_completed_now_confirm_email','alert-alert-success',false);
	else{
		if(!empty($this->error))echo $this->alert($this->error,'alert-error',false);
		echo $this->form($this->form);
?>
<fieldset>
	<legend><?=$this->translate('or_use_another_service')?></legend>
    <a class="btn btn-mini" href="<?=$this->url('AccessControl/Authenticate',array('service'=>'facebook'))?>"><i class="icon-facebook"></i> Facebook</a>
    <a class="btn btn-mini" href="<?=$this->url('AccessControl/Authenticate',array('service'=>'twitter'))?>"><i class="icon-twitter"></i> Twitter</a>
    <a class="btn btn-mini" href="<?=$this->url('AccessControl/Authenticate',array('service'=>'google'))?>"><i class="icon-google-plus"></i> Google+</a>
</fieldset>
<?php } ?>