<h3><?=$this->layout()->title?></h3>
<?php
if($this->credentialReset === true)echo $this->alert('password_reset_sent','alert-success',false);
else{
	if(!empty($this->error)){
		if($this->error === $this->translate('auth_access_pending'))$this->error .= '
			: <a href="javascript:oController.sendConfirmationEmail('.$this->escapeHtmlAttr($this->escapeJson($this->form->get('auth_access_identity')->getValue())).');">'.strtolower($this->translate('resend_confirmation_email')).'</a>.
		';
		echo $this->alert(
			$this->error.'<br/><br/>
			'.$this->translate('new_user').' ? <a href="'.$this->url('AccessControl/Register').'">'.$this->translate('sign_up').'</a> !',
			'alert-error',
			false
		);
	}
	echo $this->form($this->form);
}
?>
