<h4><?=$this->translate('password_has_been_reset')?></h4>
<hr/>
<h6><?=$this->translate('this_is_your_login_information')?></h6>
<dl class="dl-horizontal">
	<dt><?=$this->translate('email')?> :</dt>
	<dd><?=$this->user_email?></dd>
	<dt><?=$this->translate('password')?> :</dt>
	<dd><?=$this->user_password?></dd>
</dl>
<hr/>
<h5>
	<a href="<?=$this->serverUrl().$this->url('User/login')?>"><?=$this->translate('sign_in')?></a>
</h5>