<?php if(isset($this->user_email,$this->user_password)){ ?>
<h4><?=$this->translate('welcome_to').' '.$this->translate('application_name')?> !</h4>
<hr/>
<h6><?=$this->translate('this_is_your_login_information')?></h6>
<dl class="dl-horizontal">
	<dt><?=$this->translate('email')?> :</dt>
	<dd><?=$this->user_email?></dd>
	<dt><?=$this->translate('password')?> :</dt>
	<dd><?=$this->user_password?></dd>
</dl>
<hr/>
<?php } ?>
<h5>
	<?=$this->translate('please_confirm_your_email')?> :
	<a href="<?=$this->serverUrl().$this->url('zf2user/confirm-email',array('registration_key'=>$this->user_registration_key))?>"><?=$this->translate('confirm_email')?></a>.
</h5>