<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title><?=$this->layout()->subject?></title>
	<?=$this->headLink()?>
</head>
<body>
	<table cellpadding="0" cellspacing="0" border="0" id="backgroundTable">
		<tr>
			<td valign="top"><?=$this->header?></td>
		</tr>
		<tr>
			<td valign="top"><div class="hero-unit"><?=$this->layout()->content?></div></td>
		</tr>
		<tr>
			<td valign="top"><?=$this->footer?></td>
		</tr>
</body>
</html>