<ul class="nav navbar-nav navbar-right">
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->layout()->authenticatedUser->getUserDisplayName()?> <b class="caret"></b></a>
		<ul class="dropdown-menu pull-right" role="menu">
			<li><a href="<?=$this->url('User/Account')?>"><?=$this->translate('account')?></a></li>
			<li><a href="<?=$this->url('AccessControl/Logout')?>"><?=$this->translate('logout')?></a></li>
		</ul>
	</li>
</ul>