<div class="navbar">
	<div class="navbar-inner">
		<a class="brand" href="<?=$this->url('home')?>"><?=$this->translate('application_name')?></a>
		<ul class="nav">
			<li class="active"><a href="<?=$this->url('home')?>"><?=$this->translate('home')?></a></li>
		</ul>
		<ul class="nav pull-right">
			<li class="menu">
				<a data-toggle="dropdown" class="dropdown-toggle" href="#"><?=$this->layout()->loggedUser->getUserEmail()?> <b class="caret"></b></a>
				<ul class="dropdown-menu menu-dropdown">
					<li class="divider"></li>
					<li><a href="<?=$this->url('zf2user/logout')?>"><?=$this->translate('logout')?></a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>