<div class="navbar">
	<div class="navbar-inner">
		<a class="brand" href="<?=$this->url('home')?>"><?=$this->translate('application_name')?></a>
		<ul class="nav">
			<li class="active"><a href="<?=$this->url('home')?>"><?=$this->translate('home')?></a></li>
		</ul>
		<a class="btn pull-right" href="<?=$this->url('zf2user/login')?>"><?=$this->translate('sign_in')?></a>
		<span class="pull-right nav-text">- <?=$this->translate('or')?> -</span>
		<a class="btn pull-right" href="<?=$this->url('zf2user/register')?>"><?=$this->translate('register')?></a>
	</div>
</div>